# Copyright 2025 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

# Generate certs missing from unicorn images
autoGenerateCert: true

registry: cgr.dev
# renovate: datasource=docker depName=cgr.dev/defenseunicorns.com/neuvector-controller-fips versioning=docker
tag: "5.5.1"

manager:
  image:
    repository: defenseunicorns.com/neuvector-manager

enforcer:
  image:
    repository: defenseunicorns.com/neuvector-enforcer-fips

controller:
  image:
    repository: defenseunicorns.com/neuvector-controller-fips

cve:
  scanner:
    image:
      registry: docker.io
      repository: neuvector/scanner
      tag: "6"
    volumes:
      - name: internal-cert-dir
        emptyDir:
          sizeLimit: 50Mi
    volumeMounts:
      - mountPath: /etc/neuvector/certs/internal/
        name: internal-cert-dir
  updater:
    enabled: true
    image:
      repository: defenseunicorns.com/curl-fips
      # renovate: datasource=docker depName=cgr.dev/defenseunicorns.com/curl-fips versioning=docker
      tag: "8.20.0-dev"
