# Copyright 2025 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

registry: docker.io
# renovate: datasource=docker depName=docker.io/neuvector/controller versioning=docker
tag: "5.6.1"
manager:
  image:
    repository: neuvector/manager
enforcer:
  image:
    repository: neuvector/enforcer

controller:
  image:
    repository: neuvector/controller

cve:
  scanner:
    image:
      repository: neuvector/scanner
      tag: "6"
    volumes:
      - name: internal-cert-dir
        emptyDir:
          sizeLimit: 50Mi
    volumeMounts:
      - mountPath: /etc/neuvector/certs/internal/
        name: internal-cert-dir

  updater:
    enabled: true
    image:
      repository: neuvector/updater
      # renovate: datasource=docker depName=docker.io/neuvector/updater versioning=docker
      tag: "0.0.14"
