# Copyright 2025 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial


# TODO: This is a hack service to work around the lack of support for adding labels to the NeuVector manager service
# Remove when upstream supports this: https://github.com/neuvector/neuvector-helm/pull/487
apiVersion: v1
kind: Service
metadata:
  name: uds-neuvector-service-webui
  namespace: {{ .Release.Namespace }}
  labels:
    # These labels enforce that traffic to the manager pod goes through the waypoint proxy
    istio.io/ingress-use-waypoint: "true"
    istio.io/use-waypoint: neuvector-manager-waypoint
spec:
  type: ClusterIP
  ports:
    - port: 8443
      name: manager
      protocol: TCP
  selector:
    app: neuvector-manager-pod
