# Copyright 2025 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

tasks:
  - name: all
    actions:
      - task: health-check
      - task: ingress
      - task: e2e

  # Ensure application deploys successfully and becomes available
  - name: health-check
    actions:
      - description: Wait for NeuVector Job Completion
        cmd: |
          # On upgrades there may be cert rotation jobs or other jobs that run
          if ./uds zarf tools kubectl get jobs -n neuvector --no-headers 2>/dev/null | grep -q .; then
            ./uds zarf tools kubectl wait --for=condition=complete job --all -n neuvector --timeout=5m
          fi
      - description: Validate NeuVector Controller
        wait:
          cluster:
            kind: Deployment
            name: neuvector-controller-pod
            condition: Available
            namespace: neuvector
      - description: Validate NeuVector Enforcer
        wait:
          cluster:
            kind: Pod
            name: app=neuvector-enforcer-pod
            condition: Ready
            namespace: neuvector
      - description: Validate NeuVector Manager
        wait:
          cluster:
            kind: Deployment
            name: neuvector-manager-pod
            condition: Available
            namespace: neuvector
      - description: Validate NeuVector Interface
        wait:
          network:
            protocol: https
            address: neuvector.admin.uds.dev
            code: 200
      - description: Validate NeuVector Scanner
        wait:
          cluster:
            kind: Deployment
            name: neuvector-scanner-pod
            condition: Available
            namespace: neuvector

  - name: ingress
    actions:
      - description: NeuVector UI Status Check
        maxRetries: 30
        cmd: |
          STATUS=$(curl -L -o /dev/null -s -w "%{http_code}\n" https://neuvector.admin.uds.dev)
          echo "NeuVector system status: ${STATUS}"
          if [ "$STATUS" != "200" ]; then
            sleep 10
            exit 1
          fi

  - name: e2e
    description: Run NeuVector E2E Tests
    actions:
      - description: NeuVector UI Checks
        cmd: |
          # renovate: datasource=docker depName=mcr.microsoft.com/playwright versioning=docker
          docker run --rm --ipc=host --net=host --mount type=bind,source="$(pwd)",target=/app mcr.microsoft.com/playwright:v1.55.1-noble sh -c " \
            cd app && \
            npm ci && \
            npx playwright test \
            "
        dir: tests
      - description: Trigger updater job and wait for all job completion
        cmd: |
          kubectl delete job updater -n neuvector >/dev/null 2>&1 || true # Clean up previous runs if necessary
          kubectl create job --from=cronjob/neuvector-updater-pod updater -n neuvector
          if ./uds zarf tools kubectl get jobs -n neuvector --no-headers 2>/dev/null | grep -q .; then
            ./uds zarf tools kubectl wait --for=condition=complete job --all -n neuvector --timeout=5m
          fi
