# Copyright 2025 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

name: Release

on:
  push:
    branches:
      - main

# Permissions for the GITHUB_TOKEN used by the workflow.
permissions:
  contents: read # Allows reading the content of the repository.
  packages: read # Allows reading the content of the repository's packages.
  id-token: write

jobs:
  publish:
    permissions:
      contents: write # Allows writing the content of the repository.
      packages: write # Allows writing the content of the repository's packages.
      id-token: write
    strategy:
      matrix:
        flavor: [upstream, registry1, unicorn]
        architecture: [amd64, arm64]
    uses: defenseunicorns/uds-common/.github/workflows/callable-publish.yaml@4f46bb2110abc2c994ad242b099822de71de1ecc # v1.20.5
    with:
      flavor: ${{ matrix.flavor }}
      options: --set BASE_REPO="ghcr.io/uds-packages"
      runsOn: ${{ matrix.architecture == 'arm64' && 'appstore-4-core-arm64' || 'appstore-4-core-amd64' }}
      uds-releaser: true
    secrets: inherit # Inherits all secrets from the parent workflow.
