# Copyright 2025 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

name: Test

on:
  # This workflow is triggered on pull requests to the main branch.
  pull_request:
    # milestoned is added here so that a PR can be re-triggered if it is milestoned.
    types: [milestoned, opened, reopened, synchronize]

# Permissions for the GITHUB_TOKEN used by the workflow.
permissions:
  contents: read # Allows reading the content of the repository.
  packages: read # Allows reading the content of the repository's packages.
  pull-requests: read
  id-token: write

# Abort prior jobs in the same workflow / PR
concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-flavor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: test-flavor
        uses: defenseunicorns/uds-common/.github/actions/test-flavor@4f46bb2110abc2c994ad242b099822de71de1ecc # v1.20.5
        id: test-flavor
    outputs:
      upgrade-flavors: ${{ steps.test-flavor.outputs.upgrade-flavors }}

  validate:
    needs: check-flavor
    strategy:
      fail-fast: false
      matrix:
        type: [install, upgrade]
        flavor: [upstream, unicorn, registry1]
    uses: defenseunicorns/uds-common/.github/workflows/callable-test.yaml@4f46bb2110abc2c994ad242b099822de71de1ecc # v1.20.5
    with:
      timeout: 30
      options: --set BASE_REPO="ghcr.io/uds-packages"
      runsOn: appstore-8-core-amd64
      upgrade-flavors: ${{ needs.check-flavor.outputs.upgrade-flavors }}
      flavor: ${{ matrix.flavor }}
      type: ${{ matrix.type }}
    secrets: inherit # Inherits all secrets from the parent workflow.

  verify-test:
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - name: Success
        run: echo "All tests passed successfully!"
